# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clips', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('income', models.IntegerField()),
                ('area', models.FloatField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Households')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Households')),
            ],
        ),
        migrations.AddField(
            model_name='farms',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Households'),
        ),
        migrations.AddField(
            model_name='audio',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Households'),
        ),
    ]
